name: Update Data

on:
  schedule:
    - cron: '0 * * * *' #Every hour 
  workflow_dispatch:  # Manually

permissions:
  contents: write  # Esto permite al bot hacer push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up git to push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{secrets.GH_TOKEN}}@github.com/Hephaestus520/RETO4-MLOPS.git
 
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.20' 
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script 
        run: python data_extraction/extract_data.py

      - name: Update Data
        run: |
          bash ./data_extraction/update_data.sh 

      - name: Verify GCP credentials secret (safe check)
        run: |
          if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
            echo "❌ Secret GCP_CREDENTIALS is NOT available!"
            echo "👉 This usually happens if:"
            echo "   - The workflow runs from a fork (secrets don’t pass)"
            echo "   - The secret name is misspelled (should be exactly GCP_CREDENTIALS)"
            echo "   - The secret was never added in GitHub Settings → Secrets → Actions"
            exit 1
          else
            echo "✅ Secret GCP_CREDENTIALS is available and injected correctly!"
            echo "🔒 (Content hidden for safety)"
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload CSV to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: data/data.csv
          destination: donostia-parking-data/raw/data.csv
