name: Update Data

on:
  schedule:
    - cron: '0 * * * *' #Every hour 
  workflow_dispatch:  # Manually

permissions:
  contents: write  # Esto permite al bot hacer push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up git to push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{secrets.GH_TOKEN}}@github.com/Hephaestus520/RETO4-MLOPS.git
 
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.20' 
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script 
        run: python data_extraction/extract_data.py

      - name: Update Data
        run: |
          bash ./data_extraction/update_data.sh 

      - name: Debug secret length
        run: |
          echo "Checking secret length..."
          echo "${{ secrets.GCP_CREDENTIALS }}" | wc -c
          echo "${{secrets.GH_TOKEN}}" | wc -c

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload CSV to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: data/data.csv
          destination: donostia-parking-data/raw/data.csv
